steps:
  # [HOOK: beforeDeploy]

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'validate-environment'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/cht-utils.sh
        echo "Starting validate-environment"
        echo "validate_environment \"${PROJECT_ID}\" \"${_APP_VERSION}\" \"${_REGION}\" \"${_REPOSITORY}\""
        validate_environment "${PROJECT_ID}" "${_APP_VERSION}" "${_REGION}" "${_REPOSITORY}"

  # [HOOK: beforeBuild]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/cht-utils.sh
        echo "Starting build-image"
        echo "build_and_push_image \"${PROJECT_ID}\" \"${_APP_VERSION}\" \"${_REGION}\" \"${_REPOSITORY}\" \"$$GITHUB_PACKAGES_TOKEN\""
        build_and_push_image "${PROJECT_ID}" "${_APP_VERSION}" "${_REGION}" "${_REPOSITORY}" "$$GITHUB_PACKAGES_TOKEN"
    secretEnv: ['GITHUB_PACKAGES_TOKEN']

  # [HOOK: beforeServiceDeploy]

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/cht-utils.sh
        echo "Starting deploy_to_cloud_run"
        echo "deploy_to_cloud_run \"${PROJECT_ID}\" \"${_APP_VERSION}\" \"${_REGION}\" \"${_REPOSITORY}\""
        deploy_to_cloud_run "${PROJECT_ID}" "${_APP_VERSION}" "${_REGION}" "${_REPOSITORY}"

  # [HOOK: afterDeploy]

substitutions:
  _APP_VERSION: 'TEST'
  _REGION: 'us-central1'
  _REPOSITORY: 'cloud-run-source-deploy'
  _GITHUB_PACKAGES_TOKEN: '' # This will be set in Cloud Build UI

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_PACKAGES_TOKEN/versions/latest
      env: 'GITHUB_PACKAGES_TOKEN'
